language: clang
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - lcov

install:
  - gem install coveralls-lcov

script:
  - make test

after_success:
  - coveralls-lcov /home/travis/build/genomicsplc/variantkey/target/test/coverage/variantkey.info
