package:
  name: r-variantkey
  version: 1.2.0

source:
  path: ../..

build:
  number: 1

rpaths:
  - lib/R/lib/
  - lib/

requirements:
  build:
    - gcc
    - r-base
    - r-inline
    - r-pryr
    - r-Rcpp
  run:
    - libgcc
    - r-base

test:
  requires:
    - r-base
    - r-testthat
  imports:
    - r-variantkey

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: Genetic VariantKey R Library
